# Generated by Django 3.1.5 on 2021-01-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_csvfile_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
