# Generated by Django 3.1.5 on 2021-01-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210122_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='customer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='item',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
