# Generated by Django 3.1.5 on 2021-01-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210122_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='customer',
            new_name='gems',
        ),
        migrations.RenameField(
            model_name='csvfile',
            old_name='quantity',
            new_name='spent_money',
        ),
        migrations.RenameField(
            model_name='csvfile',
            old_name='item',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='total',
        ),
    ]
